### ISSUE TITLE
Missing Trakt parameters

### ISSUE THREAD

**Issue by gmikulski** [permster/trakt-to-couchpotato#2]
Hi,

This is very interesting script. Could you just give a hint where I can find below things?:

- Trakt client id
- Trakt client secret
- Trakt access token
- Trakt refresh token

Many thanks!

**Comment by permster** [comment]
It's difficult to explain but I'll give it a shot.  Basically you just need to follow the steps to set up an application using the trakt api found here: http://docs.trakt.apiary.io/

1. [Create a new trakt application](https://trakt.tv/oauth/applications/new) on the trakt site.  You can make up the name but I called mine the name of the script "trakt-to-couchpotato".  The redirect uri should be "urn:ietf:wg:oauth:2.0:oob".  After completing this you should get a client id and client secret assigned to your app.

2. Authorize your new application using API call directly in browser.  This is basically associating the new application to your trakt account.  The response from this API call should be a pin (authorization code).
[https://trakt.tv/oauth/authorize?response_type=code&client_id=<client_id>&redirect_uri=urn:ietf:wg:oauth:2.0:oob](https://trakt.tv/oauth/authorize?response_type=code&client_id=<client_id>f&redirect_uri=urn:ietf:wg:oauth:2.0:oob)

3. Exchange authorization code (pin) from the previous step to obtain an oauth token.  This next step is a POST call so you can't technically do it directly in the browser.  You can use PostMan (separate download) to do this easily.  (In PostMan) Just change it to POST, paste in the below URL, click the params button, populate each parameter field and hit send.
[https://api.trakt.tv/oauth/token?code=<pin_from_trakt>&client_id=<client_id>&client_secret=<client_secret>&redirect_uri=urn:ietf:wg:oauth:2.0:oob&grant_type=authorization_code](https://api.trakt.tv/oauth/token?code=<pin_from_trakt>&client_id=<client_id>&client_secret=<client_secret>&redirect_uri=urn:ietf:wg:oauth:2.0:oob&grant_type=authorization_code)

4. Populate the client id, client secret, access token, and refresh token taken from the previous API calls into the config.ini.

That should be it!  This is a one time process so long as you run the script periodically it will keep your token up to date for you so that you don't have to perform steps 2 and 3 again.

**Comment by gmikulski** [comment]
Thanks for your hints and sorry for late reply. I did try this, but on point 3 I get the error:

404 "Come, my lord, you are a long way from home and winter is coming."

Reply I get on point 2 is a code that is 8 characters long… Is it correct?
Client ID and client secret are quite long, maybe different format?

Kind regards and all the best for 2017!
Grzegorz

**Comment by permster** [comment]
Sorry for the delayed response.  I was away on holiday.

I just updated my original post.  I had a typo in the URL on step 2 above and I updated a few things in step 3.  I followed the steps myself and I think everything is in there.  Hope that helps.

**Comment by gmikulski** [comment]
Thanks a lot, it works!! :)

For anyone who is reading this, in point 3 I would just add:
https://api.trakt.tv/oauth/token?code=**<pin_from_trakt>**&client_id=<client_id>&client_secret=<client_secret>&redirect_uri=urn:ietf:wg:oauth:2.0:oob&grant_type=authorization_code

Many thanks for your time!
